Repository tscenping/BE, pull requests merged in 2023-12, with the labels that each got.

#49 feat: added new queries(isJoined, avatar, ... ) and change Error messages
  src/channels/channels.controller.ts
  src/channels/channels.repository.ts
  src/channels/channels.service.ts
  src/channels/dto/creat-channel-request.dto.ts
  src/channels/dto/dmchannel-list-return.dto.ts
Labels: enhancement

#51 feat: 더미데이터 sql 파일 생성
  database/dummy.sql
  database/init.sql
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/channels/channel-users.repository.ts
  src/channels/channels.gateway.ts
  src/channels/channels.module.ts
  src/channels/channels.repository.ts
  src/channels/channels.service.spec.ts
  src/channels/channels.service.ts
  src/config/typeorm.config.ts
  src/main.ts
  src/users/blocks.repository.ts
  src/users/blocks.service.ts
  src/users/entities/user.entity.ts
  src/users/friends.repository.ts
  src/users/friends.service.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: FEAT

#61 feat(users): change '/ranks' without guards, pagination to chunked data
  src/users/ranks.service.ts
  src/users/users.controller.ts
Labels: FEAT, FIX

#64 Yubin
  src/channels/channels.controller.ts
  src/channels/channels.gateway.ts
  src/channels/channels.service.ts
  src/channels/dto/event-message-on.dto.ts
  src/common/exception/custom-exception.ts
  src/common/exception/custom-ws-exception.filter.ts
  src/common/exception/error-code.ts
  src/main.ts
  src/socket-adapter/socket-io.adapter.ts
Labels: FEAT

#72 fix(channel): recover joinChannelRoom logic also add notice dto
  src/channels/channels.controller.ts
  src/channels/channels.gateway.ts
  src/channels/dto/event-message-on.dto.ts
Labels: FIX

#73 fix(channels): omit enterchannelId logic
  src/channels/channels.controller.ts
Labels: FIX

#76 WIP: add channels accept, refuse logic
  src/channels/channel-invitation.repository.ts
  src/channels/channels.controller.ts
  src/channels/channels.gateway.ts
  src/channels/channels.service.ts
  src/channels/dto/channel-Invitation-list-response.dto.ts
  src/channels/dto/channel-Invitation-list-return.dto.ts
  src/channels/dto/channel-Invitation.dto.ts
  src/channels/dto/delete-invitation-param.dto.ts
  src/channels/dto/delete-invitations-param.dto.ts
  src/game/dto/gateway-create-channelInvitation-param-dto.ts
Labels: FEAT

#77 fix: PROTECTED 채널에서 비밀번호 검증 함수에 await 추가 #16
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/entities/channel.entity.ts
Labels: FIX

#78 WIP: /channels/accept 리턴 타입 수정 및 /channels/notice 구현 진행 중 #52
  src/channels/channels.controller.ts
  src/channels/channels.gateway.ts
  src/channels/dto/channel-notice.response.dto.ts
  src/channels/dto/event-message-on.dto.ts
  src/common/enum.ts
Labels: FIX, WIP

#79 inivite 요청에 대해 accept, refuse로직을 구현했습니다.
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/dto/channel-Invitation-list-response.dto.ts
Labels: FEAT

#80 - feat: /channels/notice 구현 #52
  src/channels/channels.controller.ts
  src/channels/channels.gateway.ts
  src/channels/channels.service.ts
  src/channels/dto/channel-notice.response.dto.ts
  src/common/enum.ts
Labels: FEAT

#82 fix: kick, ban, mute, admin 시 notice 소켓 이벤트 수정
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
Labels: FIX

#83 fix: kick, ban에서 channelId를 찾지 못하는 오류 수정 #52
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
Labels: FIX

#86 feat(channels): add try-catch logic and validate duplicated user
  src/channels/channel-users.repository.ts
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
Labels: FEAT

#94 feat(game): clear gameQueue when client disconnected
  src/channels/channels.gateway.ts
  src/channels/channels.service.ts
  src/channels/entities/channel.entity.ts
  src/game/game.module.ts
  src/game/game.service.ts
Labels: bug, FIX

#100 fix: 프로필 조회 시 rank value 수정
  src/channels/channels.service.ts
  src/users/dto/user-profile.dto.ts
  src/users/users.repository.ts
Labels: FIX
